### ISSUE TITLE
HE Reference matrix

### ISSUE THREAD

**Issue by krishnakanagal** [BiomedSciAI/histocartography#28]
Hi,

I had a question regarding Macenko Stain Normalizer. I see that the H&E Reference matrix is a hard coded matrix of shape (2, 3). Can you shed some light on how did you get this matrix? I am looking for a paper where this matrix is provided. Below is the line of code which I am referring to in the code _histocartography/preprocessing/stain_normalizers.py_

```
self.stain_matrix_target = np.array(
                [[0.5626, 0.7201, 0.4062], [0.2159, 0.8012, 0.5581]]
```

**Comment by PushpakPati** [comment]
The stain matrix is extracted from a reference image using the Macenko algorithm.
The script histocartography/preprocessing/stain_normalizers.py also allows to pass your own reference image to extract the matrix.
