### ISSUE TITLE
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor' 

### ISSUE THREAD

**Issue by esratepe** [BiomedSciAI/histocartography#30]
# 2. nuclei detection 
    nuclei_map, nuclei_centroids = nuclei_detector.process(image)

I had error this line . Could you help me ? 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-dd8adab0dc18> in <module>()
     40 
     41     # 2. nuclei detection
---> 42     nuclei_map, nuclei_centroids = nuclei_detector.process(image)
     43 
     44     # 3. nuclei feature extraction

11 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
   1184                 return modules[name]
   1185         raise AttributeError("'{}' object has no attribute '{}'".format(
-> 1186             type(self).__name__, name))
   1187 
   1188     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

**Comment by spencerkrichevsky** [comment]
Looks like torch has to be downgraded for now:

`pip install torch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1`
