### ISSUE TITLE
Nuclei instance types

### ISSUE THREAD

**Issue by Abbas009** [BiomedSciAI/histocartography#31]
Really appreciate your work guys.
Can we draw an instance map for the specific type of nuclei? e.g only epithelium etc. From nuclei extractor or during visualization?
Example Images are in the link:
https://drive.google.com/drive/folders/1giWG6V-daElfYHtVMnFeAdbm2D_Efmcp?usp=sharing

**Comment by PushpakPati** [comment]
Currently, we do not have the nuclei classification integrated in the library.

You can download the original [HoVerNet model](https://github.com/vqdang/hover_net) and pass to the nuclei detector to get the nuclei instance map for all nuclei types.
