### ISSUE TITLE
Weights instead of model

### ISSUE THREAD

**Issue by Ramxnan** [BiomedSciAI/histocartography#35]
Nuclei_extraction.py gives an option to use our own model instead of the existing model created by pannuke dataset.

In my case i have the model weights and not the model itself, how would i have to adapt the code to run the nuclei detector with just my model weights?

![image](https://user-images.githubusercontent.com/84337058/187026028-2a7d58a2-81a5-4568-b880-86c4831c38f9.png)

**Comment by PushpakPati** [comment]
You need to create the model architecture, load the model weights, and then pass to the nuclei detector.
