### ISSUE TITLE
Graph creation doesn't behave properly when used in patho-quant-explainer

### ISSUE THREAD

**Issue by CarlinLiao** [BiomedSciAI/histocartography#39]
See [these](https://github.com/histocartography/patho-quant-explainer/issues/9) [three](https://github.com/histocartography/patho-quant-explainer/issues/8) [issues](https://github.com/histocartography/patho-quant-explainer/issues/7) in the patho-quant-explainer repository.

To summarize, I was trying to reproduce the results shown in the pathology quantitative explainer paper, but failed to do so. After doing debugging and traceback I found that it was because the nuclei extractor detects too few nuclei even on the original (latest) BRACS dataset. One example would be detecting only 4 nuclei in `BRACS_1897_DCIS_4.png`. The lack of nuclei sometimes causes the DeepFeatureExtractor to fail, which then causes the KNNGraphBuilder to fail and the graph output to file function to throw an error.

I've also tried running the patho-quant-explainer pipeline on the previous version of the dataset, but that method fails on the very first graph in the test set because the KNNGraphBuilder fails to run, causing a save error.

Since I made no modifications to the source code, this could be due to an environment or hardware issue. [As mentioned in another issue,](https://github.com/BiomedSciAI/histocartography/issues/38) the environment yaml provided in any of the histocartography repositories appear to be incomplete, outdated, or both. If this error isn't replicated by the maintenance team, would you be able to provide the exact environment you're using? Thanks!

**Comment by PushpakPati** [comment]
The error you faced might be due to different library versions. 

You can follow the updated requirements and environment information to create the correct conda env.
For GPU, please install pytorch, torchvision and DGL GPU compatible libraries (instructions in the README)
