### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by SaharAlmahfouzNasser** [BiomedSciAI/histocartography#43]
Hi, I am trying to run the example you provided, but I am getting the following error at the line (feature_extractor = DeepFeatureExtractor(architecture='resnet34', patch_size=72)):
"RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1."

Any idea why I am getting this error?
Thanks!

**Comment by PushpakPati** [comment]
Hi
This is a CUDA compute capability error, not a histocartography error.
Please check this thread: https://github.com/pytorch/pytorch/issues/31285
This may be a solution: https://github.com/pytorch/pytorch/issues/31285#issuecomment-1120438920
