### ISSUE TITLE
Error: cannot import name 'greycomatrix' from 'skimage.feature' while importing histocartography

### ISSUE THREAD

**Issue by akhila1729** [BiomedSciAI/histocartography#48]
greycomatrix is renamed to graycomatrix but it seems like the historiography code still uses the name greycomatrix in the code.
Please suggest a way to resolve this issue.
The error:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/62430823/224470084-1eb0f494-25a3-4df1-b7f6-b457515f32d7.png">

versions:
histocartography : -0.2.1
scikit-image-0.20.0

**Comment by Petas14** [comment]
from skimage.feature.texture import graycomatrix
